const games = [
  { title: "1 on 1 soccer", url: "https://bucket1.8classes.com/games/1on1soccer/index.html", img: "./images/thumbnails/1on1soccer.jpg", genre: "arcade" },
  { title: "10 minutes till dawn", url: "https://bucket1.8classes.com/games/10minutestilldawn/index.html", img: "./images/thumbnails/10minutestilldawn.jpg", genre: "arcade" },
  { title: "1v1lol", url: "https://bucket1.8classes.com/games/1v1lol/index.html", img: "./images/thumbnails/1v1lol.jpg", genre: "arcade" },
  { title: "2048", url: "https://bucket1.8classes.com/games/2048/index.html", img: "./images/thumbnails/2048.jpg", genre: "puzzle" },
  { title: "abuda the alien", url: "https://bucket1.8classes.com/games/abudathealien/index.html", img: "./images/thumbnails/abudathealien.jpg", genre: "adventure" },
  { title: "ace attorney", url: "https://bucket1.8classes.com/games/aceattorney/index.html", img: "./images/thumbnails/aceattorney.jpg", genre: "puzzle" },
  { title: "achievement unlocked", url: "https://bucket1.8classes.com/games/achievementunlocked/index.html", img: "./images/thumbnails/achievementunlocked.jpg", genre: "puzzle" },
  { title: "achievement unlocked 2", url: "https://bucket1.8classes.com/games/achievementunlocked2/index.html", img: "./images/thumbnails/achievementunlocked2.jpg", genre: "puzzle" },
  { title: "achievement unlocked 3", url: "https://bucket1.8classes.com/games/achievementunlocked3/index.html", img: "./images/thumbnails/achievementunlocked3.jpg", genre: "puzzle" },
  { title: "adofai", url: "https://bucket1.8classes.com/games/adofai/index.html", img: "./images/thumbnails/adofai.jpg", genre: "arcade" },
  { title: "advance wars", url: "https://bucket1.8classes.com/games/advancewars/index.html", img: "./images/thumbnails/advancewars.jpg", genre: "adventure" },
  { title: "advance wars 2", url: "https://bucket1.8classes.com/games/advancewars2/index.html", img: "./images/thumbnails/advancewars2.jpg", genre: "adventure" },
  { title: "advance wars days of ruin", url: "https://bucket1.8classes.com/games/advancewarsdayofruin/index.html", img: "./images/thumbnails/advancewarsdaysofruin.jpg", genre: "adventure" },
  { title: "adventure captialist", url: "https://bucket1.8classes.com/games/adventurecapitalist/index.html", img: "./images/thumbnails/adventurecaptialist.jpg", genre: "simulation" },
  { title: "adventure time", url: "https://bucket1.8classes.com/games/adventuretime/index.html", img: "./images/thumbnails/adventuretimeheyiceking.jpg", genre: "adventure" },
  { title: "age of war", url: "https://bucket1.8classes.com/games/ageofwar/index.html", img: "./images/thumbnails/ageofwar.jpg", genre: "arcade" },
  { title: "age of war 2", url: "https://bucket1.8classes.com/games/ageofwar2/index.html", img: "./images/thumbnails/ageofwar2.jpg", genre: "arcade" },
  { title: "altered beast", url: "https://bucket1.8classes.com/games/alteredbeast/index.html", img: "./images/thumbnails/alteredbeast.jpg", genre: "platformer" },
  { title: "amazing rope police", url: "https://bucket1.8classes.com/games/amazingropepolice/index.html", img: "./images/thumbnails/amazingropepolice.jpg", genre: "adventure" },
  { title: "among us fangame", url: "https://bucket1.8classes.com/games/amongus/index.html", img: "./images/thumbnails/amongus.jpg", genre: "arcade" },
  { title: "amorphous", url: "https://bucket1.8classes.com/games/amorphous/index.html", img: "./images/thumbnails/amorphous.jpg", genre: "amorphous" },
  { title: "animal crossing", url: "https://bucket1.8classes.com/games/animalcrossingwildworld/index.html", img: "./images/thumbnails/animalcrossingwildworld.jpg", genre: "simulation" },
  { title: "aquapark slides", url: "https://bucket1.8classes.com/games/aquaparkslides/index.html", img: "./images/thumbnails/aquaparkslides.jpg", genre: "arcade" },
  { title: "backrooms 2d", url: "https://bucket1.8classes.com/games/backrooms2d/index.html", img: "./images/thumbnails/backrooms2d.jpg", genre: "adventure" },
  { title: "bad ice cream", url: "https://bucket1.8classes.com/games/badicecream/index.html", img: "./images/thumbnails/badicecream.jpg", genre: "arcade" },
  { title: "bad ice cream 2", url: "https://bucket1.8classes.com/games/badicecream2/index.html", img: "./images/thumbnails/badicecream2.jpg", genre: "arcade" },
  { title: "bad ice cream 3", url: "https://bucket1.8classes.com/games/badicecream3/index.html", img: "./images/thumbnails/badicecream3.jpg", genre: "arcade" },
  { title: "bad piggies", url: "https://bucket1.8classes.com/games/badpiggies/index.html", img: "./images/thumbnails/badpiggies.jpg", genre: "arcade" },
  { title: "bad time simulator", url: "https://bucket1.8classes.com/games/badtimesimulator/index.html", img: "./images/thumbnails/badtimesimulator.jpg", genre: "simulation" },
  { title: "baldi's basics", url: "https://bucket1.8classes.com/games/baldisbasics/index.html", img: "./images/thumbnails/baldisbasics.jpg", genre: "adventure" },
  { title: "ballistic chickens", url: "https://bucket1.8classes.com/games/ballisticchickens/index.html", img: "./images/thumbnails/ballisticchickens.jpg", genre: "arcade" },
  { title: "balloon run", url: "https://bucket1.8classes.com/games/balloonrun/index.html", img: "./images/thumbnails/balloonrun.jpg", genre: "arcade" },
  { title: "banjo kazooie", url: "https://bucket1.8classes.com/games/banjokazooie/index.html", img: "./images/thumbnails/banjokazooie.jpg", genre: "platformer" },
  { title: "banjo pilot", url: "https://bucket1.8classes.com/games/banjopilot/index.html", img: "./images/thumbnails/banjopilot.jpg", genre: "arcade" },
  { title: "banjo tooie", url: "https://bucket1.8classes.com/games/banjotooie/index.html", img: "./images/thumbnails/banjotooie.jpg", genre: "platformer" },
  { title: "basket random", url: "https://bucket1.8classes.com/games/basketrandom/index.html", img: "./images/thumbnails/basketrandom.jpg", genre: "arcade" },
  { title: "basketbros io", url: "https://bucket1.8classes.com/games/basketbrosio/index.html", img: "./images/thumbnails/basketbrosio.jpg", genre: "mobile" },
  { title: "battle beavers", url: "https://bucket1.8classes.com/games/battlebeavers/index.html", img: "./images/thumbnails/battlebeavers.jpg", genre: "arcade" },
  { title: "battleships", url: "https://bucket1.8classes.com/games/battleships/index.html", img: "./images/thumbnails/battleships.jpg", genre: "arcade" },
  { title: "battletoads", url: "https://bucket1.8classes.com/games/battletoads/index.html", img: "./images/thumbnails/battletoads.jpg", genre: "adventure" },
  { title: "big red button", url: "https://bucket1.8classes.com/games/bigredbutton/index.html", img: "./images/thumbnails/bigredbutton.jpg", genre: "puzzle" },
  { title: "bike champ 2", url: "https://bucket1.8classes.com/games/bikechamp2/index.html", img: "./images/thumbnails/bikechamp2.jpg", genre: "arcade" },
  { title: "bitlife", url: "https://bucket1.8classes.com/games/bitlife/index.html", img: "./images/thumbnails/bitlife.jpg", genre: "simulator" },
  { title: "block blast", url: "https://bucket1.8classes.com/games/blockblast/index.html", img: "./images/thumbnails/blockblast.jpg", genre: "puzzle" },
  { title: "bloxors", url: "https://bucket1.8classes.com/games/bloxors/index.html", img: "./images/thumbnails/bloxors.jpg", genre: "puzzle" },
  { title: "bob the robber 2", url: "https://bucket1.8classes.com/games/bobtherobber2/index.html", img: "./images/thumbnails/bobtherobber2.jpg", genre: "adventure" },
  { title: "bomberman", url: "https://bucket1.8classes.com/games/bomberman/index.html", img: "./images/thumbnails/bomberman.jpg", genre: "arcade" },
  { title: "bowsers inside story", url: "https://bucket1.8classes.com/games/bowsersinsidestory/index.html", img: "./images/thumbnails/bowsersinsidestory.jpg", genre: "simulation" },
  { title: "boxing physics 2", url: "https://bucket1.8classes.com/games/boxingphysics2/index.html", img: "./images/thumbnails/boxingphysics2.jpg", genre: "arcade" },
  { title: "boxing random", url: "https://bucket1.8classes.com/games/boxingrandom/index.html", img: "./images/thumbnails/boxingrandom.jpg", genre: "arcade" },
  { title: "brawl stars project laser", url: "https://bucket1.8classes.com/games/brawlstarsprojectlaser/index.html", img: "./images/thumbnails/brawlstarsprojectlaser.jpg", genre: "arcade" },
  { title: "breaking the bank", url: "https://bucket1.8classes.com/games/breakingthebank/index.html", img: "./images/thumbnails/breakingthebank.jpg", genre: "adventure" },
  { title: "btd", url: "https://bucket1.8classes.com/games/btd/btd/index.html", img: "./images/thumbnails/btd.jpg", genre: "arcade" },
  { title: "btd 2", url: "https://bucket1.8classes.com/games/btd/btd2/index.html", img: "./images/thumbnails/btd2.jpg", genre: "arcade" },
  { title: "btd 3", url: "https://bucket1.8classes.com/games/btd/btd3/index.html", img: "./images/thumbnails/btd3.jpg", genre: "arcade" },
  { title: "btd 4", url: "https://bucket1.8classes.com/games/btd/btd4/index.html", img: "./images/thumbnails/btd4.jpg", genre: "arcade" },
  { title: "btd 5", url: "https://bucket1.8classes.com/games/btd/btd5/index.html", img: "./images/thumbnails/btd5.jpg", genre: "arcade" },
  { title: "bubble spinner", url: "https://bucket1.8classes.com/games/bubblespinner/index.html", img: "./images/thumbnails/bubblespinner.jpg", genre: "arcade" },
  { title: "bubble tanks 2", url: "https://bucket1.8classes.com/games/bubbletanks2/index.html", img: "./images/thumbnails/bubbletanks2.jpg", genre: "arcade" },
  { title: "burger and frights", url: "https://bucket1.8classes.com/games/burgerandfrights/index.html", img: "./images/thumbnails/burgerandfrights.jpg", genre: "adventure" },
  { title: "burrito bison", url: "https://bucket1.8classes.com/games/burritobison/index.html", img: "./images/thumbnails/burritobison.jpg", genre: "arcade" },
  { title: "cactus mccoy", url: "https://bucket1.8classes.com/games/cactusmccoy/index.html", img: "./images/thumbnails/cactusmccoy.jpg", genre: "platformer" },
  { title: "cactus mccoy 2", url: "https://bucket1.8classes.com/games/cactusmccoy2/index.html", img: "./images/thumbnails/cactusmccoy2.jpg", genre: "platformer" },
  { title: "canopy", url: "https://bucket1.8classes.com/games/canopy/index.html", img: "./images/thumbnails/canopy.jpg", genre: "platformer" },
  { title: "cars 2", url: "https://bucket1.8classes.com/games/cars2/index.html", img: "./images/thumbnails/cars2.jpg", genre: "adventure" },
  { title: "castlevania", url: "https://bucket1.8classes.com/games/castlevania/index.html", img: "./images/thumbnails/castlevania.jpg", genre: "adventure" },
  { title: "castlevania", url: "https://bucket1.8classes.com/games/castlevaniaiii/index.html", img: "./images/thumbnails/castlevania.jpg", genre: "adventure" },
  { title: "castlevania aria of sorrow", url: "https://bucket1.8classes.com/games/castlevaniaariaofsorrow/index.html", img: "./images/thumbnails/castlevaniaariaofsorrow.jpg", genre: "arcade" },
  { title: "castlevania dawn of sorrow", url: "https://bucket1.8classes.com/games/castlevaniadawnofsorrow/index.html", img: "./images/thumbnails/castlevaniadawnofsorrow.jpg", genre: "adventure" },
  { title: "cave chaos", url: "https://bucket1.8classes.com/games/cavechaos/index.html", img: "./images/thumbnails/cavechaos.jpg", genre: "platformer" },
  { title: "celeste", url: "https://bucket1.8classes.com/games/celeste/index.html", img: "./images/thumbnails/celeste.jpg", genre: "platformer" },
  { title: "cell machine", url: "https://bucket1.8classes.com/games/cellmachine/index.html", img: "./images/thumbnails/cellmachine.jpg", genre: "puzzle" },
  { title: "champion island", url: "https://bucket1.8classes.com/games/championisland/index.html", img: "./images/thumbnails/championisland.jpg", genre: "adventure" },
  { title: "change type", url: "https://bucket1.8classes.com/games/changetype/index.html", img: "./images/thumbnails/changetype.jpg", genre: "platformer" },
  { title: "cheese dreams", url: "https://bucket1.8classes.com/games/cheesedreams/index.html", img: "./images/thumbnails/cheesedreams.jpg", genre: "platformer" },
  { title: "chess", url: "https://bucket1.8classes.com/games/chess/index.html", img: "./images/thumbnails/chess.jpg", genre: "arcade" },
  { title: "chibi knight", url: "https://bucket1.8classes.com/games/chibiknight/index.html", img: "./images/thumbnails/chibiknight.jpg", genre: "adventure" },
  { title: "chisel", url: "https://bucket1.8classes.com/games/chisel/index.html", img: "./images/thumbnails/chisel.jpg", genre: "puzzle" },
  { title: "chisel 2", url: "https://bucket1.8classes.com/games/chisel2/index.html", img: "./images/thumbnails/chisel2.jpg", genre: "puzzle" },
  { title: "choose your weapon", url: "https://bucket1.8classes.com/games/chooseyourweapon/index.html", img: "./images/thumbnails/chooseyourweapon.jpg", genre: "platformer" },
  { title: "choose your weapon 2", url: "https://bucket1.8classes.com/games/chooseyourweapon2/index.html", img: "./images/thumbnails/chooseyourweapon2.jpg", genre: "platformer" },
  { title: "choose your weapon 3", url: "https://bucket1.8classes.com/games/chooseyourweapon3/index.html", img: "./images/thumbnails/chooseyourweapon3.jpg", genre: "platformer" },
  { title: "chrome dino game", url: "https://bucket1.8classes.com/games/dinogame/index.html", img: "./images/thumbnails/chromedino.jpg", genre: "arcade" },
  { title: "chrono trigger", url: "https://bucket1.8classes.com/games/chronotrigger/index.html", img: "./images/thumbnails/chronotrigger.jpg", genre: "adventure" },
  { title: "clicker heroes", url: "https://bucket1.8classes.com/games/clickerheroes/index.html", img: "./images/thumbnails/clickerheroes.jpg", genre: "arcade" },
  { title: "cluster rush", url: "https://bucket1.8classes.com/games/clusterrush/index.html", img: "./images/thumbnails/clusterrush.jpg", genre: "platformer" },
  { title: "color switch", url: "https://bucket1.8classes.com/games/colorswitch/index.html", img: "./images/thumbnails/colorswitch.jpg", genre: "arcade" },
  { title: "comix zone", url: "https://bucket1.8classes.com/games/comixzone/index.html", img: "./images/thumbnails/comixzone.jpg", genre: "arcade" },
  { title: "connect 4", url: "https://bucket1.8classes.com/games/connect4/index.html", img: "./images/thumbnails/connect4.jpg", genre: "arcade" },
  { title: "contra", url: "https://bucket1.8classes.com/games/contra/index.html", img: "./images/thumbnails/contra.jpg", genre: "adventure" },
  { title: "contra iii", url: "https://bucket1.8classes.com/games/contraiii/index.html", img: "./images/thumbnails/contraiii.jpg", genre: "adventure" },
  { title: "control craft 2", url: "https://bucket1.8classes.com/games/controlcraft2/index.html", img: "./images/thumbnails/controlcraft2.jpg", genre: "puzzle" },
  { title: "cookie clicker", url: "https://bucket1.8classes.com/games/cookieclicker/index.html", img: "./images/thumbnails/cookieclick.jpg", genre: "arcade" },
  { title: "cooking mama", url: "https://bucket1.8classes.com/games/cookingmama/index.html", img: "./images/thumbnails/cookingmama.jpg", genre: "arcade" },
  { title: "corporation inc", url: "https://bucket1.8classes.com/games/corporationinc/index.html", img: "./images/thumbnails/corporationinc.jpg", genre: "arcade" },
  { title: "crazy tunnel 3d", url: "https://bucket1.8classes.com/games/crazytunnel3d/index.html", img: "./images/thumbnails/crazytunnel3d.jpg", genre: "arcade" },
  { title: "crimson fantasia", url: "https://bucket1.8classes.com/games/crimsonfantasia/index.html", img: "./images/thumbnails/crimsonfantasia.jpg", genre: "arcade" },
  { title: "crossy road", url: "https://bucket1.8classes.com/games/crossy/index.html", img: "./images/thumbnails/crossyroad.jpg", genre: "mobile" },
  { title: "crush the castle", url: "https://bucket1.8classes.com/games/crushthecastle/index.html", img: "./images/thumbnails/crushthecastle.jpg", genre: "puzzle" },
  { title: "crush the castle 2", url: "https://bucket1.8classes.com/games/crushthecastle2/index.html", img: "./images/thumbnails/crushthecastle2.jpg", genre: "puzzle" },
  { title: "csgo clicker", url: "https://bucket1.8classes.com/games/csgoclicker/index.html", img: "./images/thumbnails/csgoclicker.jpg", genre: "arcade" },
  { title: "cubefield", url: "https://bucket1.8classes.com/games/cubefield/index.html", img: "./images/thumbnails/cubefield.jpg", genre: "arcade" },
  { title: "cut the rope", url: "https://bucket1.8classes.com/games/cuttherope/index.html", img: "./images/thumbnails/cuttherope.jpg", genre: "mobile" },
  { title: "dadish", url: "https://bucket1.8classes.com/games/dadish/index.html", img: "./images/thumbnails/dadish.jpg", genre: "platformer" },
  { title: "dadish 2", url: "https://bucket1.8classes.com/games/dadish2/index.html", img: "./images/thumbnails/dadish2.jpg", genre: "platformer" },
  { title: "dadish 3", url: "https://bucket1.8classes.com/games/dadish3/index.html", img: "./images/thumbnails/dadish3.jpg", genre: "platformer" },
  { title: "dbz: supersonic warriors", url: "https://bucket1.8classes.com/games/dbzsupersonicwarriors/index.html", img: "./images/thumbnails/goldensun.jpg", genre: "arcade" },
  { title: "death run 3d", url: "https://bucket1.8classes.com/games/deathrun3d/index.html", img: "./images/thumbnails/deathrun3d.jpg", genre: "arcade" },
  { title: "defend the tank", url: "https://bucket1.8classes.com/games/defendthetank/index.html", img: "./images/thumbnails/defendthetank.jpg", genre: "arcade" },
  { title: "diddy kong racing", url: "https://bucket1.8classes.com/games/diddykongracing/index.html", img: "./images/thumbnails/diddykongracing.jpg", genre: "arcade" },
  { title: "ditto", url: "https://bucket1.8classes.com/games/ditto/index.html", img: "./images/thumbnails/ditto.jpg", genre: "platformer" },
  { title: "doge miner", url: "https://bucket1.8classes.com/games/dogeminer/index.html", img: "./images/thumbnails/dogeminer.jpg", genre: "simulator" },
  { title: "donkey kong", url: "https://bucket1.8classes.com/games/donkeykong/index.html", img: "./images/thumbnails/donkeykong.jpg", genre: "arcade" },
  { title: "donkey kong 64", url: "https://bucket1.8classes.com/games/donkeykong64/index.html", img: "./images/thumbnails/donkeykong64.jpg", genre: "platformer" },
  { title: "donkey kong country", url: "https://bucket1.8classes.com/games/donkeykongcountry/index.html", img: "./images/thumbnails/donkeykongcountry.jpg", genre: "platformer" },
  { title: "donkey kong country 2", url: "https://bucket1.8classes.com/games/donkeykongcountry2/index.html", img: "./images/thumbnails/donkeykongcountry2.jpg", genre: "platformer" },
  { title: "donkey kong country 3", url: "https://bucket1.8classes.com/games/donkeykongcountry3/index.html", img: "./images/thumbnails/donkeykongcountry3.jpg", genre: "adventure" },
  { title: "donkey kong land", url: "https://bucket1.8classes.com/games/donkeykongland/index.html", img: "./images/thumbnails/donkeykongland.jpg", genre: "platformer" },
  { title: "doodle defender", url: "https://bucket1.8classes.com/games/doodledefender/index.html", img: "./images/thumbnails/doodledefender.jpg", genre: "arcade" },
  { title: "doodle jump", url: "https://bucket1.8classes.com/games/doodlejump/index.html", img: "./images/thumbnails/doodlejump.jpg", genre: "platformer" },
  { title: "doom", url: "https://bucket1.8classes.com/games/doom/index.html", img: "./images/thumbnails/doom.jpg", genre: "arcade" },
  { title: "doom 2", url: "https://bucket1.8classes.com/games/doom2/index.html", img: "./images/thumbnails/doomii.jpg", genre: "adventure" },
  { title: "doom 64", url: "https://bucket1.8classes.com/games/doom64/index.html", img: "./images/thumbnails/doom64.jpg", genre: "adventure" },
  { title: "dr mario", url: "https://bucket1.8classes.com/games/drmario/index.html", img: "./images/thumbnails/drmario.jpg", genre: "puzzle" },
  { title: "dragon boy 2", url: "https://bucket1.8classes.com/games/dragonboy2/index.html", img: "./images/thumbnails/dragonboy2.jpg", genre: "adventure" },
  { title: "drift boss", url: "https://bucket1.8classes.com/games/driftboss/index.html", img: "./images/thumbnails/driftboss.jpg", genre: "mobile" },
  { title: "drift hunters", url: "https://bucket1.8classes.com/games/drifthunters/index.html", img: "./images/thumbnails/drifthunters.jpg", genre: "adventure" },
  { title: "drift mania", url: "https://bucket1.8classes.com/games/driftmania/index.html", img: "./images/thumbnails/driftmania.jpg", genre: "arcade" },
  { title: "drill dozer", url: "https://bucket1.8classes.com/games/drilldozer/index.html", img: "./images/thumbnails/drilldozer.jpg", genre: "arcade" },
  { title: "duck life", url: "https://bucket1.8classes.com/games/ducklife/index.html", img: "./images/thumbnails/ducklife.jpg", genre: "simulation" },
  { title: "duck life 2", url: "https://bucket1.8classes.com/games/ducklife2/index.html", img: "./images/thumbnails/ducklife2.jpg", genre: "simulation" },
  { title: "duck life 3", url: "https://bucket1.8classes.com/games/ducklife3/index.html", img: "./images/thumbnails/ducklife3.jpg", genre: "simulation" },
  { title: "duck life 4", url: "https://bucket1.8classes.com/games/ducklife4/index.html", img: "./images/thumbnails/ducklife4.jpg", genre: "simulation" },
  { title: "duck life 5", url: "https://bucket1.8classes.com/games/ducklife5/index.html", img: "./images/thumbnails/ducklife5.jpg", genre: "simulation" },
  { title: "duck life 6", url: "https://bucket1.8classes.com/games/ducklife6/index.html", img: "./images/thumbnails/ducklife6.jpg", genre: "simulation" },
  { title: "duck tales", url: "https://bucket1.8classes.com/games/ducktales/index.html", img: "./images/thumbnails/ducktales.jpg", genre: "adventure" },
  { title: "duke nukem 64", url: "https://bucket1.8classes.com/games/dukenukem64/index.html", img: "./images/thumbnails/dukenukem64.jpg", genre: "arcade" },
  { title: "duke nukem advance", url: "https://bucket1.8classes.com/games/dukenukemadvance/index.html", img: "./images/thumbnails/dukenukemadvance.jpg", genre: "arcade" },
  { title: "earthbound", url: "https://bucket1.8classes.com/games/earthbound/index.html", img: "./images/thumbnails/earthbound.jpg", genre: "adventure" },
  { title: "ecco the dolphin", url: "https://bucket1.8classes.com/games/eccothedolphin/index.html", img: "./images/thumbnails/eccothedolphin.jpg", genre: "adventure" },
  { title: "edge surf", url: "https://bucket1.8classes.com/games/surf/index.html", img: "./images/thumbnails/surf.jpg", genre: "arcade" },
  { title: "electric box", url: "https://bucket1.8classes.com/games/electricbox/index.html", img: "./images/thumbnails/electricbox.jpg", genre: "puzzle" },
  { title: "electric man 2", url: "https://bucket1.8classes.com/games/electricman2/index.html", img: "./images/thumbnails/electricman2.jpg", genre: "aracde" },
  { title: "escaping the prison", url: "https://bucket1.8classes.com/games/escapingtheprison/index.html", img: "./images/thumbnails/escapingtheprison.jpg", genre: "adventure" },
  { title: "excitebike 64", url: "https://bucket1.8classes.com/games/excitebike64/index.html", img: "./images/thumbnails/excitebike64.jpg", genre: "arcade" },
  { title: "f-zero", url: "https://bucket1.8classes.com/games/fzero/index.html", img: "./images/thumbnails/fzero.jpg", genre: "arcade" },
  { title: "f-zero x", url: "https://bucket1.8classes.com/games/fzerox/index.html", img: "./images/thumbnails/fzerox.jpg", genre: "arcade" },
  { title: "factory balls", url: "https://bucket1.8classes.com/games/factoryballs/index.html", img: "./images/thumbnails/factoryballs.jpg", genre: "arcade" },
  { title: "fancy pants adventure", url: "https://bucket1.8classes.com/games/fancypantsadventure/index.html", img: "./images/thumbnails/fancypantsadventure.jpg", genre: "platformer" },
  { title: "fancy pants adventure 2", url: "https://bucket1.8classes.com/games/fancypantsadventure2/index.html", img: "./images/thumbnails/fancypantsadventure2.jpg", genre: "adventure" },
  { title: "fancy pants adventure 3", url: "https://bucket1.8classes.com/games/fancypantsadventure3/index.html", img: "./images/thumbnails/fancypantsadventure3.jpg", genre: "platformer" },
  { title: "feed me", url: "https://bucket1.8classes.com/games/feedme/index.html", img: "./images/thumbnails/feedme.jpg", genre: "platformer" },
  { title: "final fantasy iv", url: "https://bucket1.8classes.com/games/finalfantasyvi/index.html", img: "./images/thumbnails/finalfantasyiv.jpg", genre: "adventure" },
  { title: "final fantasy tactics adv", url: "https://bucket1.8classes.com/games/finalfantasytacticsadvance/index.html", img: "./images/thumbnails/finalfantasytacticsadventure.jpg", genre: "arcade" },
  { title: "final ninja", url: "https://bucket1.8classes.com/games/finalninja/index.html", img: "./images/thumbnails/finalninja.jpg", genre: "platformer" },
  { title: "fire emblem", url: "https://bucket1.8classes.com/games/fireemblem/index.html", img: "./images/thumbnails/fireemblem.jpg", genre: "adventure" },
  { title: "fireboy and watergirl", url: "https://bucket1.8classes.com/games/fireboywatergirl/index.html", img: "./images/thumbnails/fireboyandwatergirl.jpg", genre: "platformer" },
  { title: "flappy bird", url: "https://bucket1.8classes.com/games/flappy/index.html", img: "./images/thumbnails/flappybird.jpg", genre: "mobile" },
  { title: "flappy dunk", url: "https://bucket1.8classes.com/games/FlappyDunk/index.html", img: "./images/thumbnails/flappydunk.jpg", genre: "mobile" },
  { title: "fleeing the complex", url: "https://bucket1.8classes.com/games/fleeingthecomplex/index.html", img: "./images/thumbnails/fleeingthecomplex.jpg", genre: "adventure" },
  { title: "flippy fish", url: "https://bucket1.8classes.com/games/flippyfish/index.html", img: "./images/thumbnails/flippyfish.jpg", genre: "arcade" },
  { title: "flood runner 2", url: "https://bucket1.8classes.com/games/floodrunner2/index.html", img: "./images/thumbnails/floodrunner2.jpg", genre: "platformer" },
  { title: "flood runner 3", url: "https://bucket1.8classes.com/games/floodrunner3/index.html", img: "./images/thumbnails/floodrunner3.jpg", genre: "platformer" },
  { title: "fnaf 1", url: "https://bucket1.8classes.com/games/fnaf/index.html", img: "./images/thumbnails/fnaf.jpg", genre: "adventure" },
  { title: "fnaf 2", url: "https://bucket1.8classes.com/games/fnaf-2/index.html", img: "./images/thumbnails/fnaf2.jpg", genre: "adventure" },
  { title: "fnaf 3", url: "https://bucket1.8classes.com/games/fnaf-3/index.html", img: "./images/thumbnails/fnaf3.jpg", genre: "adventure" },
  { title: "fnaf 4", url: "https://bucket1.8classes.com/games/fnaf-4/index.html", img: "./images/thumbnails/fnaf4.jpg", genre: "adventure" },
  { title: "fnf mid fight masses", url: "https://bucket1.8classes.com/games/fnfmidfight/index.html", img: "./images/thumbnails/midfightmasses.jpg", genre: "arcade" },
  { title: "friday night funkin", url: "https://bucket1.8classes.com/games/fnf/index.html", img: "./images/thumbnails/fnf.jpg", genre: "arcade" },
  { title: "frost bite", url: "https://bucket1.8classes.com/games/frostbite/index.html", img: "./images/thumbnails/frostbite.jpg", genre: "platformer" },
  { title: "frost bite 2", url: "https://bucket1.8classes.com/games/frostbite2/index.html", img: "./images/thumbnails/frostbite2.jpg", genre: "platformer" },
  { title: "fruit ninja", url: "https://bucket1.8classes.com/games/fruitninja/index.html", img: "./images/thumbnails/fruitninja.jpg", genre: "arcade" },
  { title: "funny mad racing", url: "https://bucket1.8classes.com/games/funnymadracing/index.html", img: "./images/thumbnails/funnymadracing.jpg", genre: "arcade" },
  { title: "funny shooter 2", url: "https://bucket1.8classes.com/games/funnyshooter2/index.html", img: "./images/thumbnails/funnyshooter2.jpg", genre: "arcade" },
  { title: "garfield gets real", url: "https://bucket1.8classes.com/games/garfieldgetsreal/index.html", img: "./images/thumbnails/garfieldgetsreal.jpg", genre: "adventure" },
  { title: "geometry dash lite", url: "https://bucket1.8classes.com/games/gdlite/index.html", img: "./images/thumbnails/geometrydashlite.jpg", genre: "platformer" },
  { title: "geometry dash sky", url: "https://bucket1.8classes.com/games/geometrydashsky/index.html", img: "./images/thumbnails/geometrydashsky.jpg", genre: "platformer" },
  { title: "geometry rash", url: "https://bucket1.8classes.com/games/geometryrash/index.html", img: "./images/thumbnails/geometryrash.jpg", genre: "platformer" },
  { title: "getaway shootout", url: "https://bucket1.8classes.com/games/getawayshootout/index.html", img: "./images/thumbnails/getawayshootout.jpg", genre: "arcade" },
  { title: "gex 64", url: "https://bucket1.8classes.com/games/gex64/index.html", img: "./images/thumbnails/gex64.jpg", genre: "platformer" },
  { title: "go ball", url: "https://bucket1.8classes.com/games/goball/index.html", img: "./images/thumbnails/goball.jpg", genre: "arcade" },
  { title: "gold digger frvr", url: "https://bucket1.8classes.com/games/golddiggerfrvr/index.html", img: "./images/thumbnails/golddiggerfrvr.jpg", genre: "simulation" },
  { title: "golden axe", url: "https://bucket1.8classes.com/games/goldenaxe/index.html", img: "./images/thumbnails/goldenaxe.jpg", genre: "adventure" },
  { title: "golden eye 007", url: "https://bucket1.8classes.com/games/goldeneye007/index.html", img: "./images/thumbnails/goldeneye007.jpg", genre: "adventure" },
  { title: "golden sun", url: "https://bucket1.8classes.com/games/goldensun/index.html", img: "./images/thumbnails/goldensun.jpg", genre: "adventure" },
  { title: "grand theft grotto", url: "https://bucket1.8classes.com/games/grandtheftgrotto/index.html", img: "./images/thumbnails/grandtheftgrotto.jpg", genre: "arcade" },
  { title: "gun fest", url: "https://bucket1.8classes.com/games/gunfest/index.html", img: "./images/thumbnails/gunfest.jpg", genre: "puzzle" },
  { title: "gun mayhem", url: "https://bucket1.8classes.com/games/gunmayhem/index.html", img: "./images/thumbnails/gunmayhem.jpg", genre: "arcade" },
  { title: "gun mayhem 2", url: "https://bucket1.8classes.com/games/gunmayhem2/index.html", img: "./images/thumbnails/gunmayhem2.jpg", genre: "arcade" },
  { title: "gun mayhem redux", url: "https://bucket1.8classes.com/games/gunmayhemredux/index.html", img: "./images/thumbnails/gunmayhemredux.jpg", genre: "arcade" },
  { title: "gunstar heroes", url: "https://bucket1.8classes.com/games/gunstarheroes/index.html", img: "./images/thumbnails/gunstarheroes.jpg", genre: "arcade" },
  { title: "happy wheels", url: "https://bucket1.8classes.com/games/happywheels/index.html", img: "./images/thumbnails/happywheels.jpg", genre: "arcade" },
  { title: "harvest moon", url: "https://bucket1.8classes.com/games/harvestmoon/index.html", img: "./images/thumbnails/harvestmoon.jpg", genre: "simulation" },
  { title: "harvest moon 64", url: "https://bucket1.8classes.com/games/harvestmoon64/index.html", img: "./images/thumbnails/harvestmoon64.jpg", genre: "simulation" },
  { title: "helix jump", url: "https://bucket1.8classes.com/games/helixjump/index.html", img: "./images/thumbnails/helixjump.jpg", genre: "mobile" },
  { title: "hexgl", url: "https://bucket1.8classes.com/games/hexgl/index.html", img: "./images/thumbnails/hexgl.jpg", genre: "arcade" },
  { title: "hole io", url: "https://bucket1.8classes.com/games/holeio/index.html", img: "./images/thumbnails/holeio.jpg", genre: "arcade" },
  { title: "house of hazards", url: "https://bucket1.8classes.com/games/houseofhazards/index.html", img: "./images/thumbnails/houseofhazards.jpg", genre: "platformer" },
  { title: "ice climber", url: "https://bucket1.8classes.com/games/iceclimber/index.html", img: "./images/thumbnails/iceclimber.jpg", genre: "arcade" },
  { title: "icebreaker", url: "https://bucket1.8classes.com/games/icebreaker/index.html", img: "./images/thumbnails/icebreaker.jpg", genre: "puzzle" },
  { title: "illusion of gaia", url: "https://bucket1.8classes.com/games/illusionofgaia/index.html", img: "./images/thumbnails/illusionofgaia.jpg", genre: "simulation" },
  { title: "infiltrating the airship", url: "https://bucket1.8classes.com/games/infiltratingtheairship/index.html", img: "./images/thumbnails/infiltratingtheairship.jpg", genre: "adventure" },
  { title: "infinite craft", url: "https://bucket1.8classes.com/games/infinitecraft/index.html", img: "./images/thumbnails/infinitecraft.jpg", genre: "simulation" },
  { title: "jet force gemini", url: "https://bucket1.8classes.com/games/jetforcegemini/index.html", img: "./images/thumbnails/jetforcegemini.jpg", genre: "arcade" },
  { title: "jetpack joyride", url: "https://bucket1.8classes.com/games/jetpackjoyride/index.html", img: "./images/thumbnails/jetpackjoyride.jpg", genre: "arcade" },
  { title: "just fall lol", url: "https://bucket1.8classes.com/games/justfalllol/index.html", img: "./images/thumbnails/justfalllol.jpg", genre: "arcade" },
  { title: "kid icarus", url: "https://bucket1.8classes.com/games/kidicarus/index.html", img: "./images/thumbnails/kidicarus.jpg", genre: "arcade" },
  { title: "kirby 64", url: "https://bucket1.8classes.com/games/kirby64/index.html", img: "./images/thumbnails/kirby64.jpg", genre: "platformer" },
  { title: "kirby amazing mirror", url: "https://bucket1.8classes.com/games/kirbyamazingmirror/index.html", img: "./images/thumbnails/kirbyamazingmirror.jpg", genre: "platformer" },
  { title: "kirby mass attack", url: "https://bucket1.8classes.com/games/kirbymassattack/index.html", img: "./images/thumbnails/kirbymassattack.jpg", genre: "adventure" },
  { title: "kirby power paintbrush", url: "https://bucket1.8classes.com/games/kirbypowerpaintbrush/index.html", img: "./images/thumbnails/kirbypowerpaintbrush.jpg", genre: "adventure" },
  { title: "kirby's dream land", url: "https://bucket1.8classes.com/games/kirbysdreamland/index.html", img: "./images/thumbnails/kirbysdreamland.jpg", genre: "platformer" },
  { title: "kirby's dreamland 2", url: "https://bucket1.8classes.com/games/kirbysdreamland2/index.html", img: "./images/thumbnails/kirbysdreamland2.jpg", genre: "platformer" },
  { title: "knife hit", url: "https://bucket1.8classes.com/games/knifehit/index.html", img: "./images/thumbnails/knifehit.jpg", genre: "arcade" },
  { title: "lazy jump 3d", url: "https://bucket1.8classes.com/games/lazyjump3d/index.html", img: "./images/thumbnails/lazyjump3d.jpg", genre: "arcade" },
  { title: "learn to fly", url: "https://bucket1.8classes.com/games/learntofly/index.html", img: "./images/thumbnails/learntofly.jpg", genre: "arcade" },
  { title: "learn to fly 2", url: "https://bucket1.8classes.com/games/learntofly2/index.html", img: "./images/thumbnails/learntofly2.jpg", genre: "adventure" },
  { title: "learn to fly 3", url: "https://bucket1.8classes.com/games/learntofly3/index.html", img: "./images/thumbnails/learntofly3.jpg", genre: "arcade" },
  { title: "lego batman", url: "https://bucket1.8classes.com/games/legobatman/index.html", img: "./images/thumbnails/legobatman.jpg", genre: "adventure" },
  { title: "line rider", url: "https://bucket1.8classes.com/games/linerider/index.html", img: "./images/thumbnails/linerider.jpg", genre: "platformer" },
  { title: "link to the past", url: "https://bucket1.8classes.com/games/linktothepast/index.html", img: "./images/thumbnails/linktothepast.jpg", genre: "adventure" },
  { title: "link's awakening dx", url: "https://bucket1.8classes.com/games/linksawakeningdx/index.html", img: "./images/thumbnails/linksawakeningdx.jpg", genre: "adventure" },
  { title: "lows adventures 2", url: "https://bucket1.8classes.com/games/lowsadventures2/index.html", img: "./images/thumbnails/lowsadventures2.jpg", genre: "adventure" },
  { title: "majora's mask", url: "https://bucket1.8classes.com/games/majorasmask/index.html", img: "./images/thumbnails/majorasmask.jpg", genre: "adventure" },
  { title: "mario combat", url: "https://bucket1.8classes.com/games/mariocombat/index.html", img: "./images/thumbnails/mariocombat.jpg", genre: "platformer" },
  { title: "mario golf", url: "https://bucket1.8classes.com/games/mariogolf/index.html", img: "./images/thumbnails/mariogolf.jpg", genre: "arcade" },
  { title: "mario kart 64", url: "https://bucket1.8classes.com/games/mariokart64/index.html", img: "./images/thumbnails/mariokart64.jpg", genre: "arcade" },
  { title: "mario kart ds", url: "https://bucket1.8classes.com/games/mariokartds/index.html", img: "./images/thumbnails/mariokartds.jpg", genre: "arcade" },
  { title: "mario kart super circuit", url: "https://bucket1.8classes.com/games/mariokartsupercircuit/index.html", img: "./images/thumbnails/mariokartsupercircuit.jpg", genre: "arcade" },
  { title: "mario paint", url: "https://bucket1.8classes.com/games/mariopaint/index.html", img: "./images/thumbnails/mariopaint.jpg", genre: "arcade" },
  { title: "mario party", url: "https://bucket1.8classes.com/games/marioparty/index.html", img: "./images/thumbnails/marioparty.jpg", genre: "arcade" },
  { title: "mario party 2", url: "https://bucket1.8classes.com/games/marioparty2/index.html", img: "./images/thumbnails/marioparty2.jpg", genre: "arcade" },
  { title: "mario party 3", url: "https://bucket1.8classes.com/games/marioparty3/index.html", img: "./images/thumbnails/marioparty3.jpg", genre: "arcade" },
  { title: "mario party advance", url: "https://bucket1.8classes.com/games/mariopartyadvance/index.html", img: "./images/thumbnails/mariopartyadvance.jpg", genre: "arcade" },
  { title: "mario party ds", url: "https://bucket1.8classes.com/games/mariopartyds/index.html", img: "./images/thumbnails/mariopartyds.jpg", genre: "arcade" },
  { title: "mario pinball land", url: "https://bucket1.8classes.com/games/mariopinballland/index.html", img: "./images/thumbnails/mariopinballland.jpg", genre: "arcade" },
  { title: "mario tennis", url: "https://bucket1.8classes.com/games/mariotennis/index.html", img: "./images/thumbnails/mariotennis.jpg", genre: "arcade" },
  { title: "mc tower defence 2", url: "https://bucket1.8classes.com/games/mctowerdefence2/index.html", img: "./images/thumbnails/mctowerdefence2.jpg", genre: "arcade" },
  { title: "mega man 2", url: "https://bucket1.8classes.com/games/megaman2/index.html", img: "./images/thumbnails/megaman2.jpg", genre: "platformer" },
  { title: "mega man x", url: "https://bucket1.8classes.com/games/megamanx/index.html", img: "./images/thumbnails/megamanx.jpg", genre: "platformer" },
  { title: "mega man zero", url: "https://bucket1.8classes.com/games/megamanzero/index.html", img: "./images/thumbnails/megamanzero.jpg", genre: "platformer" },
  { title: "metal gear solid", url: "https://bucket1.8classes.com/games/metalgearsolid/index.html", img: "./images/thumbnails/metalgearsolid.jpg", genre: "adventure" },
  { title: "metroid", url: "https://bucket1.8classes.com/games/metroid/index.html", img: "./images/thumbnails/metroid.jpg", genre: "adventure" },
  { title: "metroid fusion", url: "https://bucket1.8classes.com/games/metroidfusion/index.html", img: "./images/thumbnails/metroidfusion.jpg", genre: "adventure" },
  { title: "metroid ii", url: "https://bucket1.8classes.com/games/metroidii/index.html", img: "./images/thumbnails/metroidii.jpg", genre: "platformer" },
  { title: "minecraft [v1.5.2]", url: "https://bucket1.8classes.com/games/mc/index.html", img: "./images/thumbnails/mc.jpg", genre: "minecraft" },
  { title: "minecraft [v1.8]", url: "https://bucket1.8classes.com/games/eagler1.8/index.html", img: "./images/thumbnails/mc1.8.jpg", genre: "minecraft" },
  { title: "minesweeper", url: "https://bucket1.8classes.com/games/minesweeper/index.html", img: "./images/thumbnails/minesweeper.jpg", genre: "puzzle" },
  { title: "monkey mart", url: "https://bucket1.8classes.com/games/monkeymart/index.html", img: "./images/thumbnails/monkeymart.jpg", genre: "simulation" },
  { title: "monopoly", url: "https://bucket1.8classes.com/games/monopoly/index.html", img: "./images/thumbnails/monopoly.jpg", genre: "arcade" },
  { title: "monster brawl", url: "https://bucket1.8classes.com/games/monsterbrawl/index.html", img: "./images/thumbnails/monsterbrawl.jpg", genre: "arcade" },
  { title: "mortal kombat 4", url: "https://bucket1.8classes.com/games/mortalkombat4/index.html", img: "./images/thumbnails/mortalkombat4.jpg", genre: "arcade" },
  { title: "mother 3", url: "https://bucket2.8classes.com/games/mother3/index.html", img: "./images/thumbnails/mother3.jpg", genre: "adventure" },
  { title: "motox3m", url: "https://bucket2.8classes.com/games/motox3m/index.html", img: "./images/thumbnails/motox3m.jpeg", genre: "platformer" },
  { title: "motox3m pool", url: "https://bucket2.8classes.com/games/motox3mpool/index.html", img: "./images/thumbnails/motox3mpool.jpg", genre: "platformer" },
  { title: "motox3m spooky", url: "https://bucket2.8classes.com/games/motox3mspooky/index.html", img: "./images/thumbnails/motox3mspooky.jpg", genre: "platformer" },
  { title: "motox3m winter", url: "https://bucket2.8classes.com/games/motox3mwinter/index.html", img: "./images/thumbnails/motox3mwinter.jpg", genre: "platformer" },
  { title: "multitask", url: "https://bucket2.8classes.com/games/multitask/index.html", img: "./images/thumbnails/multitask.jpg", genre: "arcade" },
  { title: "mutiny", url: "https://bucket2.8classes.com/games/mutiny/index.html", img: "./images/thumbnails/mutiny.jpg", genre: "platformer" },
  { title: "mystery dungeon", url: "https://bucket2.8classes.com/games/pokemonmysterydungeon/index.html", img: "./images/thumbnails/pokemonmysterydungeon.jpg", genre: "adventure" },
  { title: "mystical ninja", url: "https://bucket2.8classes.com/games/mysticalninja/index.html", img: "./images/thumbnails/mysticalninja.jpg", genre: "adventure" },
  { title: "neon rider", url: "https://bucket2.8classes.com/games/neonrider/index.html", img: "./images/thumbnails/neonrider.jpg", genre: "arcade" },
  { title: "new super mario bros", url: "https://bucket2.8classes.com/games/newsupermariobros/index.html", img: "./images/thumbnails/newsupermariobros.jpg", genre: "platformer" },
  { title: "ngon", url: "https://bucket2.8classes.com/games/ngon/index.html", img: "./images/thumbnails/ngon.jpg", genre: "arcade" },
  { title: "ninja gaiden", url: "https://bucket2.8classes.com/games/ninjagaiden/index.html", img: "./images/thumbnails/ninjagaiden.jpg", genre: "adventure" },
  { title: "nintendogs", url: "https://bucket2.8classes.com/games/nintendogs/index.html", img: "./images/thumbnails/nintendogs.jpg", genre: "simulation" },
  { title: "nitrome must die", url: "https://bucket2.8classes.com/games/nitromemustdie/index.html", img: "./images/thumbnails/nitromemustdie.jpg", genre: "arcade" },
  { title: "ocarina of time", url: "https://bucket2.8classes.com/games/ocarinaoftime/index.html", img: "./images/thumbnails/ocarinaoftime.jpg", genre: "adventure" },
  { title: "offline paradise", url: "https://bucket2.8classes.com/games/offlineparadise/index.html", img: "./images/thumbnails/offlineparadise.jpg", genre: "platformer" },
  { title: "oodlegobs", url: "https://bucket2.8classes.com/games/oodlegobs/index.html", img: "./images/thumbnails/oodlegobs.jpg", genre: "platformer" },
  { title: "order of ecclesia", url: "https://bucket2.8classes.com/games/castlevaniaorderofecclesia/index.html", img: "./images/thumbnails/castlevaniaorderofecclesia.jpg", genre: "adventure" },
  { title: "osu!mania", url: "https://bucket2.8classes.com/games/osumania/index.html", img: "./images/thumbnails/osumania.jpg", genre: "arcade" },
  { title: "ovo", url: "https://bucket2.8classes.com/games/ovo/index.html", img: "./images/thumbnails/ovo.jpg", genre: "platformer" },
  { title: "pacman", url: "https://bucket2.8classes.com/games/pacman/index.html", img: "./images/thumbnails/pacman.jpg", genre: "arcade" },
  { title: "pacman world", url: "https://bucket2.8classes.com/games/pacmanworld/index.html", img: "./images/thumbnails/pacmanworld.jpg", genre: "adventure" },
  { title: "pako highway", url: "https://bucket2.8classes.com/games/pakohighway/index.html", img: "./images/thumbnails/pakohighway.jpg", genre: "arcade" },
  { title: "pandemic 2", url: "https://bucket2.8classes.com/games/pandemic2/index.html", img: "./images/thumbnails/pandemic2.jpg", genre: "simulation" },
  { title: "papa louie", url: "https://bucket2.8classes.com/games/papalouie/index.html", img: "./images/thumbnails/papalouie.jpg", genre: "platformer" },
  { title: "papa louie 2", url: "https://bucket2.8classes.com/games/papalouie2/index.html", img: "./images/thumbnails/papalouie2.jpg", genre: "platformer" },
  { title: "papa louie 3", url: "https://bucket2.8classes.com/games/papalouie3/index.html", img: "./images/thumbnails/papalouie3.jpg", genre: "platformer" },
  { title: "papa's bakeria", url: "https://bucket2.8classes.com/games/papasbakeria/index.html", img: "./images/thumbnails/papasbakeria.jpg", genre: "simulation" },
  { title: "papa's burgeria", url: "https://bucket2.8classes.com/games/papasburgeria/index.html", img: "./images/thumbnails/papasburgeria.jpg", genre: "simulation" },
  { title: "papa's cheeseria", url: "https://bucket2.8classes.com/games/papascheeseria/index.html", img: "./images/thumbnails/papascheeseria.jpg", genre: "simulation" },
  { title: "papa's cupcakeria", url: "https://bucket2.8classes.com/games/papascupcakeria/index.html", img: "./images/thumbnails/papascupcakeria.jpg", genre: "simulation" },
  { title: "papa's donuteria", url: "https://bucket2.8classes.com/games/papasdonuteria/index.html", img: "./images/thumbnails/papasdonuteria.jpg", genre: "simulation" },
  { title: "papa's freezeria", url: "https://bucket2.8classes.com/games/papasfreezeria/index.html", img: "./images/thumbnails/papasfreezeria.jpg", genre: "simulation" },
  { title: "papa's hotdoggeria", url: "https://bucket2.8classes.com/games/papashotdoggeria/index.html", img: "./images/thumbnails/papashotdoggeria.jpg", genre: "simulation" },
  { title: "papa's pancakeria", url: "https://bucket2.8classes.com/games/papaspancakeria/index.html", img: "./images/thumbnails/papaspancakeria.jpg", genre: "simulation" },
  { title: "papa's pastaria", url: "https://bucket2.8classes.com/games/papaspastaria/index.html", img: "./images/thumbnails/papaspastaria.jpg", genre: "simulation" },
  { title: "papa's pizzaria", url: "https://bucket2.8classes.com/games/papaspizzaria/index.html", img: "./images/thumbnails/papaspizzeria.jpg", genre: "simulation" },
  { title: "papa's scooperia", url: "https://bucket2.8classes.com/games/papasscooperia/index.html", img: "./images/thumbnails/papasscooperia.jpg", genre: "simulation" },
  { title: "papa's sushiria", url: "https://bucket2.8classes.com/games/papassushiria/index.html", img: "./images/thumbnails/papaswingeria.jpg", genre: "simulation" },
  { title: "papa's tacomia", url: "https://bucket2.8classes.com/games/papastacomia/index.html", img: "./images/thumbnails/papastacomia.jpg", genre: "simulation" },
  { title: "papa's wingeria", url: "https://bucket2.8classes.com/games/papaswingeria/index.html", img: "./images/thumbnails/papassushiria.jpg", genre: "simulation" },
  { title: "paper io 3d", url: "https://bucket2.8classes.com/games/paperio3d/index.html", img: "./images/thumbnails/paperio3d.jpg", genre: "arcade" },
  { title: "paper mario", url: "https://bucket2.8classes.com/games/papermario/index.html", img: "./images/thumbnails/papermario.jpg", genre: "adventure" },
  { title: "paperio2", url: "https://bucket2.8classes.com/games/paperio2/index.html", img: "./images/thumbnails/paperio2.jpg", genre: "arcade" },
  { title: "partners in time", url: "https://bucket2.8classes.com/games/marioandluigipartnersintime/index.html", img: "./images/thumbnails/marioandluigipartnersintime.jpg", genre: "platformer" },
  { title: "phantasy star iv", url: "https://bucket2.8classes.com/games/phantasystariv/index.html", img: "./images/thumbnails/phantasystariv.jpg", genre: "arcade" },
  { title: "pick crafter", url: "https://bucket2.8classes.com/games/pickcrafter/index.html", img: "./images/thumbnails/pickcrafter.jpg", genre: "arcade" },
  { title: "picross ds", url: "https://bucket2.8classes.com/games/picrossds/index.html", img: "./images/thumbnails/picrossds.jpg", genre: "puzzle" },
  { title: "pizza tower", url: "https://bucket2.8classes.com/games/pizzatower/index.html", img: "./images/thumbnails/pizzatower.jpg", genre: "platformer" },
  { title: "plants vs zombies", url: "https://bucket2.8classes.com/games/plantsvszombies/index.html", img: "./images/thumbnails/plantsvszombies.jpg", genre: "mobile" },
  { title: "pokemon diamond", url: "https://bucket2.8classes.com/games/pokemondiamond/index.html", img: "./images/thumbnails/pokemondiamond.jpg", genre: "adventure" },
  { title: "pokemon emerald", url: "https://bucket2.8classes.com/games/pokemonemerald/index.html", img: "./images/thumbnails/pokemonemerald.jpg", genre: "adventure" },
  { title: "pokemon fire red", url: "https://bucket2.8classes.com/games/pokemonfirered/index.html", img: "./images/thumbnails/pokemonfirered.jpg", genre: "adventure" },
  { title: "pokemon leaf green", url: "https://bucket2.8classes.com/games/pokemonleafgreen/index.html", img: "./images/thumbnails/pokemonleafgreen.jpg", genre: "adventure" },
  { title: "pokemon platinum", url: "https://bucket2.8classes.com/games/pokemonplatinum/index.html", img: "./images/thumbnails/pokemonplatinum.jpg", genre: "adventure" },
  { title: "pokemon ruby", url: "https://bucket2.8classes.com/games/pokemonruby/index.html", img: "./images/thumbnails/pokemonruby.jpg", genre: "adventure" },
  { title: "pokemon sapphire", url: "https://bucket2.8classes.com/games/pokemonsapphire/index.html", img: "./images/thumbnails/pokemonsapphire.jpg", genre: "adventure" },
  { title: "pokemon snap", url: "https://bucket2.8classes.com/games/pokemonsnap/index.html", img: "./images/thumbnails/pokemonsnap.jpg", genre: "adventure" },
  { title: "pokemon soulsilver", url: "https://bucket2.8classes.com/games/pokemonsoulsilver/index.html", img: "./images/thumbnails/pokemonsoulsilver.jpg", genre: "adventure" },
  { title: "pokemon stadium", url: "https://bucket2.8classes.com/games/pokemonstadium/index.html", img: "./images/thumbnails/pokemonstadium.jpg", genre: "arcade" },
  { title: "pokemon unbound", url: "https://bucket2.8classes.com/games/pokemonunbound/index.html", img: "./images/thumbnails/pokemonunbound.jpg", genre: "adventure" },
  { title: "pokemon yellow", url: "https://bucket2.8classes.com/games/pokemonyellow/index.html", img: "./images/thumbnails/pokemonyellow.jpg", genre: "adventure" },
  { title: "polytrack (og)", url: "https://bucket2.8classes.com/games/polytrack/index.html", img: "./images/thumbnails/polytrack.jpg", genre: "arcade" },
  { title: "pool", url: "https://bucket2.8classes.com/games/pool/index.html", img: "./images/thumbnails/pool.jpg", genre: "arcade" },
  { title: "portal", url: "https://bucket2.8classes.com/games/portal/index.html", img: "./images/thumbnails/portal.jpg", genre: "puzzle" },
  { title: "portal 2", url: "https://bucket2.8classes.com/games/portal2/index.html", img: "./images/thumbnails/portal2.jpg", genre: "puzzle" },
  { title: "precision client", url: "https://bucket2.8classes.com/games/precisionclient/index.html", img: "./images/thumbnails/precisionclient.jpg", genre: "minecraft" },
  { title: "professor layton", url: "https://bucket2.8classes.com/games/professorlayton/index.html", img: "./images/thumbnails/professorlayton.jpg", genre: "puzzle" },
  { title: "punch out", url: "https://bucket2.8classes.com/games/punchout/index.html", img: "./images/thumbnails/mikestysonspunchout.jpg", genre: "arcade" },
  { title: "quest 64", url: "https://bucket2.8classes.com/games/quest64/index.html", img: "./images/thumbnails/quest64.jpg", genre: "adventure" },
  { title: "rabbit samurai", url: "https://bucket2.8classes.com/games/rabbitsamurai/index.html", img: "./images/thumbnails/rabbitsamurai.jpg", genre: "platformer" },
  { title: "raft wars", url: "https://bucket2.8classes.com/games/raftwars/index.html", img: "./images/thumbnails/raftwars.jpg", genre: "arcade" },
  { title: "raft wars 2", url: "https://bucket2.8classes.com/games/raftwars2/index.html", img: "./images/thumbnails/raftwars2.jpg", genre: "arcade" },
  { title: "ranger x", url: "https://bucket2.8classes.com/games/rangerx/index.html", img: "./images/thumbnails/rangerx.jpg", genre: "arcade" },
  { title: "rayman 3", url: "https://bucket2.8classes.com/games/rayman3/index.html", img: "./images/thumbnails/rayman3.jpg", genre: "platformer" },
  { title: "recoil", url: "https://bucket2.8classes.com/games/recoil/index.html", img: "./images/thumbnails/recoil.jpg", genre: "puzzle" },
  { title: "redball", url: "https://bucket2.8classes.com/games/redball1/index.html", img: "./images/thumbnails/redball.jpg", genre: "platformer" },
  { title: "redball 3", url: "https://bucket2.8classes.com/games/redball3/index.html", img: "./images/thumbnails/redball3.jpg", genre: "platformer" },
  { title: "redball 4", url: "https://bucket2.8classes.com/games/redball4/index.html", img: "./images/thumbnails/redball4.jpg", genre: "platformer" },
  { title: "redball 4 vol 2", url: "https://bucket2.8classes.com/games/redballv2/index.html", img: "./images/thumbnails/redball4vol2.jpg", genre: "platformer" },
  { title: "redball 4 vol 3", url: "https://bucket2.8classes.com/games/redballv3/index.html", img: "./images/thumbnails/redball4vol3.jpg", genre: "platformer" },
  { title: "retro bowl", url: "https://bucket2.8classes.com/games/retrobowl/index.html", img: "./images/thumbnails/retrobowl.jpg", genre: "arcade" },
  { title: "riddle school", url: "https://bucket2.8classes.com/games/riddleschool/riddleschool1/index.html", img: "./images/thumbnails/riddleschool.jpg", genre: "puzzle" },
  { title: "riddle school 2", url: "https://bucket2.8classes.com/games/riddleschool/riddleschool2/index.html", img: "./images/thumbnails/riddleschool2.jpg", genre: "puzzle" },
  { title: "riddle school 3", url: "https://bucket2.8classes.com/games/riddleschool/riddleschool3/index.html", img: "./images/thumbnails/riddleschool3.jpg", genre: "puzzle" },
  { title: "riddle school 4", url: "https://bucket2.8classes.com/games/riddleschool/riddleschool4/index.html", img: "./images/thumbnails/riddleschool4.jpg", genre: "puzzle" },
  { title: "riddle school 5", url: "https://bucket2.8classes.com/games/riddleschool/riddleschool5/index.html", img: "./images/thumbnails/riddleschool5.jpg", genre: "puzzle" },
  { title: "riddle transfer", url: "https://bucket2.8classes.com/games/riddleschool/riddletransfer/index.html", img: "./images/thumbnails/riddletransfer.jpg", genre: "puzzle" },
  { title: "riddle transfer 2", url: "https://bucket2.8classes.com/games/riddleschool/riddletransfer2/index.html", img: "./images/thumbnails/riddletransfer2.jpg", genre: "puzzle" },
  { title: "rise higher", url: "https://bucket2.8classes.com/games/risehigher/index.html", img: "./images/thumbnails/risehigher.jpg", genre: "arcade" },
  { title: "ristar", url: "https://bucket2.8classes.com/games/ristar/index.html", img: "./images/thumbnails/ristar.jpg", genre: "adventure" },
  { title: "rocket soccer", url: "https://bucket2.8classes.com/games/rocketsoccer/index.html", img: "./images/thumbnails/rocketsoccer.jpg", genre: "arcade" },
  { title: "rooftop snipers", url: "https://bucket2.8classes.com/games/rooftop/index.html", img: "./images/thumbnails/rooftopsnipers.jpg", genre: "arcade" },
  { title: "rooftop snipers 2", url: "https://bucket2.8classes.com/games/rooftop2/index.html", img: "./images/thumbnails/rooftopsnipers2.jpg", genre: "arcade" },
  { title: "rough dino", url: "https://bucket2.8classes.com/games/roughdino/index.html", img: "./images/thumbnails/roughdino.jpg", genre: "arcade" },
  { title: "run", url: "https://bucket2.8classes.com/games/run/index.html", img: "./images/thumbnails/run.jpg", genre: "platformer" },
  { title: "run 2", url: "https://bucket2.8classes.com/games/run2/index.html", img: "./images/thumbnails/run2.jpg", genre: "platformer" },
  { title: "run 3", url: "https://bucket2.8classes.com/games/run3/index.html", img: "./images/thumbnails/run3.jpg", genre: "platformer" },
  { title: "run 3 plus", url: "https://bucket2.8classes.com/games/run3plus/index.html", img: "./images/thumbnails/run3plus.jpg", genre: "arcade" },
  { title: "sandtrix", url: "https://bucket2.8classes.com/games/sandtrix/index.html", img: "./images/thumbnails/sandtrix.jpg", genre: "arcade" },
  { title: "scapa da la dungeon", url: "https://bucket2.8classes.com/games/scapa/index.html", img: "./images/thumbnails/scapa.jpg", genre: "platformer" },
  { title: "scribblenauts", url: "https://bucket2.8classes.com/games/scribblenauts/index.html", img: "./images/thumbnails/scribblenauts.jpg", genre: "arcade" },
  { title: "shapeshipper", url: "https://bucket2.8classes.com/games/shapeshipper/index.html", img: "./images/thumbnails/shapeshipper.jpg", genre: "arcade" },
  { title: "shift", url: "https://bucket2.8classes.com/games/shift/index.html", img: "./images/thumbnails/shift.jpg", genre: "platformer" },
  { title: "shift 2", url: "https://bucket2.8classes.com/games/shift2/index.html", img: "./images/thumbnails/shift2.jpg", genre: "platformer" },
  { title: "shift 3", url: "https://bucket2.8classes.com/games/shift3/index.html", img: "./images/thumbnails/shift3.jpg", genre: "platformer" },
  { title: "shift 4", url: "https://bucket2.8classes.com/games/shift4/index.html", img: "./images/thumbnails/shift4.jpg", genre: "platformer" },
  { title: "shining force", url: "https://bucket2.8classes.com/games/shiningforce/index.html", img: "./images/thumbnails/shiningforce.jpg", genre: "arcade" },
  { title: "shinobi iii", url: "https://bucket2.8classes.com/games/shinobiiii/index.html", img: "./images/thumbnails/shinobiiii.jpg", genre: "arcade" },
  { title: "shop empire", url: "https://bucket2.8classes.com/games/shopempire/index.html", img: "./images/thumbnails/shopempire.jpg", genre: "simulation" },
  { title: "shop empire fable", url: "https://bucket2.8classes.com/games/shopempirefable/index.html", img: "./images/thumbnails/shopempirefable.jpg", genre: "simulation" },
  { title: "shrek 2", url: "https://bucket2.8classes.com/games/shrek2/index.html", img: "./images/thumbnails/shrek2.jpg", genre: "adventure" },
  { title: "simcity 2000", url: "https://bucket2.8classes.com/games/simcity/index.html", img: "./images/thumbnails/simcity2000.jpg", genre: "simulation" },
  { title: "simpsons road rage", url: "https://bucket2.8classes.com/games/simpsonsroadrage/index.html", img: "./images/thumbnails/simpsonsroadrage.jpg", genre: "arcade" },
  { title: "skibidi toilet 1v100", url: "https://bucket2.8classes.com/games/skibidi1v100/index.html", img: "./images/thumbnails/skibiditoilet1v100.jpg", genre: "platformer" },
  { title: "skywire", url: "https://bucket2.8classes.com/games/skywire/index.html", img: "./images/thumbnails/skywire.jpg", genre: "arcade" },
  { title: "skywire 2", url: "https://bucket2.8classes.com/games/skywire2/index.html", img: "./images/thumbnails/skywire2.jpg", genre: "arcade" },
  { title: "slope", url: "https://bucket2.8classes.com/games/slope/index.html", img: "./images/thumbnails/slope.jpg", genre: "platformer" },
  { title: "slope 2", url: "https://bucket2.8classes.com/games/slope2/index.html", img: "./images/thumbnails/slope2.jpg", genre: "arcade" },
  { title: "slope ball", url: "https://bucket2.8classes.com/games/slopeball/index.html", img: "./images/thumbnails/slopeball.jpg", genre: "arcade" },
  { title: "slope city", url: "https://bucket2.8classes.com/games/slopecity/index.html", img: "./images/thumbnails/slopecity.jpg", genre: "arcade" },
  { title: "snake", url: "https://bucket2.8classes.com/games/snake/index.html", img: "./images/thumbnails/snake.jpg", genre: "arcade" },
  { title: "snow battle io", url: "https://bucket2.8classes.com/games/snowbattleio/index.html", img: "./images/thumbnails/snowbattleio.jpg", genre: "arcade" },
  { title: "snow rider 3d", url: "https://bucket2.8classes.com/games/snowrider3d/index.html", img: "./images/thumbnails/snowrider3d.jpg", genre: "arcade" },
  { title: "soccer random", url: "https://bucket2.8classes.com/games/soccerrandom/index.html", img: "./images/thumbnails/soccerrandom.jpg", genre: "arcade" },
  { title: "solitaire", url: "https://bucket2.8classes.com/games/solitaire/index.html", img: "./images/thumbnails/solitaire.jpg", genre: "puzzle" },
  { title: "sonic advance", url: "https://bucket2.8classes.com/games/sonicadvance/index.html", img: "./images/thumbnails/sonicadvance.jpg", genre: "platformer" },
  { title: "sonic advance 2", url: "https://bucket2.8classes.com/games/sonicadvance2/index.html", img: "./images/thumbnails/sonicadvance2.jpg", genre: "platformer" },
  { title: "sonic and knuckles", url: "https://bucket2.8classes.com/games/sonicandknuckles/index.html", img: "./images/thumbnails/sonicandknuckles.jpg", genre: "adventure" },
  { title: "sonic rush", url: "https://bucket2.8classes.com/games/sonicrush/index.html", img: "./images/thumbnails/sonicrush.jpg", genre: "platformer" },
  { title: "sonic spinball", url: "https://bucket2.8classes.com/games/sonicspinball/index.html", img: "./images/thumbnails/sonicspinball.jpg", genre: "arcade" },
  { title: "sonic the hedgehog", url: "https://bucket2.8classes.com/games/sonicthehedgehog/index.html", img: "./images/thumbnails/sonicthehedgehog.jpg", genre: "platformer" },
  { title: "sonic the hedgehog 2", url: "https://bucket2.8classes.com/games/sonicthehedgehog2/index.html", img: "./images/thumbnails/sonicthehedgehog2.jpg", genre: "platformer" },
  { title: "sonic the hedgehog 3", url: "https://bucket2.8classes.com/games/sonicthehedgehog3/index.html", img: "./images/thumbnails/sonicthehedgehog3.jpg", genre: "platformer" },
  { title: "sort the court", url: "https://bucket2.8classes.com/games/sortthecourt/index.html", img: "./images/thumbnails/sortthecourt.jpg", genre: "simulation" },
  { title: "space invaders", url: "https://bucket2.8classes.com/games/spaceinvaders/index.html", img: "./images/thumbnails/spaceinvaders.jpg", genre: "arcade" },
  { title: "spirit tracks", url: "https://bucket2.8classes.com/games/spirittracks/index.html", img: "./images/thumbnails/spirittracks.jpg", genre: "adventure" },
  { title: "sprinter", url: "https://bucket2.8classes.com/games/sprinter/index.html", img: "./images/thumbnails/sprinter.jpg", genre: "arcade" },
  { title: "stack", url: "https://bucket2.8classes.com/games/stack/index.html", img: "./images/thumbnails/stack.jpg", genre: "arcade" },
  { title: "stair race 3d", url: "https://bucket2.8classes.com/games/stairrace3d/index.html", img: "./images/thumbnails/stairrace3d.jpg", genre: "arcade" },
  { title: "star fox 64", url: "https://bucket2.8classes.com/games/starfox64/index.html", img: "./images/thumbnails/starfox64.jpg", genre: "adventure" },
  { title: "state io", url: "https://bucket2.8classes.com/games/stateio/index.html", img: "./images/thumbnails/stateio.jpg", genre: "simulation" },
  { title: "steak and jake", url: "https://bucket2.8classes.com/games/steakandjake/index.html", img: "./images/thumbnails/steakandjake.jpg", genre: "platformer" },
  { title: "steak and jake midnight", url: "https://bucket2.8classes.com/games/steakandjakemidnightmarch/index.html", img: "./images/thumbnails/steakandjakemidnightmarch.jpg", genre: "platformer" },
  { title: "stealing the diamond", url: "https://bucket2.8classes.com/games/stealingthediamond/index.html", img: "./images/thumbnails/stealingthediamond.jpg", genre: "adventure" },
  { title: "stick war", url: "https://bucket2.8classes.com/games/stickwar/index.html", img: "./images/thumbnails/stickwar.jpg", genre: "arcade" },
  { title: "stick war 2", url: "https://bucket2.8classes.com/games/stickwar2/index.html", img: "./images/thumbnails/stickwar2.jpg", genre: "arcade" },
  { title: "stickman boost", url: "https://bucket2.8classes.com/games/stickmanboost/index.html", img: "./images/thumbnails/stickmanboost.jpg", genre: "platformer" },
  { title: "stickman climb", url: "https://bucket2.8classes.com/games/stickmanclimb/index.html", img: "./images/thumbnails/stickmanclimb.jpg", genre: "arcade" },
  { title: "stickman golf", url: "https://bucket2.8classes.com/games/stickmangolf/index.html", img: "./images/thumbnails/stickmangolf.jpg", genre: "arcade" },
  { title: "stickman hook", url: "https://bucket2.8classes.com/games/stickmanhook/index.html", img: "./images/thumbnails/stickmanhook.jpg", genre: "mobile" },
  { title: "street fighter 2", url: "https://bucket2.8classes.com/games/streetfighter2/index.html", img: "./images/thumbnails/streetfighter2.jpg", genre: "arcade" },
  { title: "streets of rage", url: "https://bucket2.8classes.com/games/streetsofrage/index.html", img: "./images/thumbnails/streetsofrage.jpg", genre: "arcade" },
  { title: "streets of rage 2", url: "https://bucket2.8classes.com/games/streetsofrage2/index.html", img: "./images/thumbnails/streetsofrage2.jpg", genre: "arcade" },
  { title: "subway runner", url: "https://bucket2.8classes.com/games/subwayrunner/index.html", img: "./images/thumbnails/subwayrunner.jpg", genre: "arcade" },
  { title: "subway surfers", url: "https://bucket2.8classes.com/games/subwaysurfers/index.html", img: "./images/thumbnails/subwaysurfers.jpeg", genre: "platformer" },
  { title: "sudoku", url: "https://bucket2.8classes.com/games/sudoku/index.html", img: "./images/thumbnails/sudoku.jpg", genre: "puzzle" },
  { title: "super bomberman", url: "https://bucket2.8classes.com/games/superbomberman/index.html", img: "./images/thumbnails/superbomberman.jpg", genre: "adventure" },
  { title: "super hot", url: "https://bucket2.8classes.com/games/superhot/index.html", img: "./images/thumbnails/superhot.jpg", genre: "adventure" },
  { title: "super mario 64", url: "https://bucket2.8classes.com/games/sm64/index.html", img: "./images/thumbnails/sm64.jpg", genre: "platformer" },
  { title: "super mario 64 ds", url: "https://bucket2.8classes.com/games/sm64ds/index.html", img: "./images/thumbnails/sm64ds.jpg", genre: "platformer" },
  { title: "super mario bros", url: "https://bucket2.8classes.com/games/supermariobros/index.html", img: "./images/thumbnails/supermariobros.jpg", genre: "platformer" },
  { title: "super mario bros 2", url: "https://bucket2.8classes.com/games/supermariobros2/index.html", img: "./images/thumbnails/supermariobros2.jpg", genre: "platformer" },
  { title: "super mario bros 3", url: "https://bucket2.8classes.com/games/supermariobros3/index.html", img: "./images/thumbnails/supermariobros3.jpg", genre: "platformer" },
  { title: "super mario construct", url: "https://bucket2.8classes.com/games/supermarioconstruct/index.html", img: "./images/thumbnails/supermarioconstruct.jpg", genre: "arcade" },
  { title: "super mario flash", url: "https://bucket2.8classes.com/games/supermarioflash/index.html", img: "./images/thumbnails/supermarioflash.jpg", genre: "platformer" },
  { title: "super mario flash 2", url: "https://bucket2.8classes.com/games/supermarioflash2/index.html", img: "./images/thumbnails/supermarioflash2.jpg", genre: "platformer" },
  { title: "super mario kart", url: "https://bucket2.8classes.com/games/supermariokart/index.html", img: "./images/thumbnails/supermariokart.jpg", genre: "arcade" },
  { title: "super mario land", url: "https://bucket2.8classes.com/games/supermarioland/index.html", img: "./images/thumbnails/supermarioland.jpg", genre: "platformer" },
  { title: "super mario land 2", url: "https://bucket2.8classes.com/games/supermarioland2/index.html", img: "./images/thumbnails/supermarioland2.jpg", genre: "adventure" },
  { title: "super mario rpg", url: "https://bucket2.8classes.com/games/supermariorpg/index.html", img: "./images/thumbnails/supermariorpg.jpg", genre: "adventure" },
  { title: "super mario world", url: "https://bucket2.8classes.com/games/supermarioworld/index.html", img: "./images/thumbnails/supermarioworld.jpg", genre: "platformer" },
  { title: "super meat boy", url: "https://bucket2.8classes.com/games/supermeatboy/index.html", img: "./images/thumbnails/supermeatboy.jpg", genre: "platformer" },
  { title: "super metroid", url: "https://bucket2.8classes.com/games/supermetroid/index.html", img: "./images/thumbnails/supermetroid.jpg", genre: "platformer" },
  { title: "super monkey ball jr", url: "https://bucket2.8classes.com/games/supermonkeyballjr/index.html", img: "./images/thumbnails/supermonkeyballjr.jpg", genre: "arcade" },
  { title: "super princess peach", url: "https://bucket2.8classes.com/games/superprincesspeach/index.html", img: "./images/thumbnails/superprincesspeach.jpg", genre: "platformer" },
  { title: "super smash bros", url: "https://bucket2.8classes.com/games/supersmashbros/index.html", img: "./images/thumbnails/supersmashbros.jpg", genre: "arcade" },
  { title: "super smash flash", url: "https://bucket2.8classes.com/games/supersmashflash/index.html", img: "./images/thumbnails/supersmashflash.jpg", genre: "arcade" },
  { title: "super tennis", url: "https://bucket2.8classes.com/games/supertennis/index.html", img: "./images/thumbnails/supertennis.jpg", genre: "arcade" },
  { title: "super treadmill", url: "https://bucket2.8classes.com/games/supertreadmill/index.html", img: "./images/thumbnails/supertreadmill.jpg", genre: "arcade" },
  { title: "superhero drop", url: "https://bucket2.8classes.com/games/superherodrop/index.html", img: "./images/thumbnails/superherodrop.jpg", genre: "puzzle" },
  { title: "superstar saga", url: "https://bucket2.8classes.com/games/superstarsaga/index.html", img: "./images/thumbnails/superstarsaga.jpg", genre: "platformer" },
  { title: "swindler", url: "https://bucket2.8classes.com/games/swindler/index.html", img: "./images/thumbnails/swindler.jpg", genre: "platformer" },
  { title: "swords and sandals", url: "https://bucket2.8classes.com/games/swordsandsandals/index.html", img: "./images/thumbnails/swordsandsandals.jpg", genre: "arcade" },
  { title: "swords and sandals 2", url: "https://bucket2.8classes.com/games/swordsandsandals2/index.html", img: "./images/thumbnails/swordsandsandals2.jpg", genre: "arcade" },
  { title: "tanuki sunset", url: "https://bucket2.8classes.com/games/tanukisunset/index.html", img: "./images/thumbnails/tanukisunset.jpg", genre: "arcade" },
  { title: "temple run 2", url: "https://bucket2.8classes.com/games/templerun2/index.html", img: "./images/thumbnails/templerun2.jpg", genre: "platformer" },
  { title: "territorial io", url: "https://bucket2.8classes.com/games/territorialio/index.html", img: "./images/thumbnails/territorialio.jpg", genre: "arcade" },
  { title: "test subject arena", url: "https://bucket2.8classes.com/games/testsubjectarena/index.html", img: "./images/thumbnails/testsubjectarena.jpg", genre: "platformer" },
  { title: "test subject complete", url: "https://bucket2.8classes.com/games/testsubjectcomplete/index.html", img: "./images/thumbnails/testsubjectcomplete.jpg", genre: "platformer" },
  { title: "tetris", url: "https://bucket2.8classes.com/games/tetris/index.html", img: "./images/thumbnails/tetris.jpg", genre: "tetris" },
  { title: "tetris ds", url: "https://bucket2.8classes.com/games/tetrisds/index.html", img: "./images/thumbnails/tetrisds.jpg", genre: "arcade" },
  { title: "the binding of isaac", url: "https://bucket2.8classes.com/games/thebindingofisaac/index.html", img: "./images/thumbnails/thebindingofisaac.jpg", genre: "adventure" },
  { title: "the impossible quiz", url: "https://bucket2.8classes.com/games/theimpossiblequiz/index.html", img: "./images/thumbnails/theimpossiblequiz.jpg", genre: "arcade" },
  { title: "the impossible quiz 2", url: "https://bucket2.8classes.com/games/theimpossiblequiz2/index.html", img: "./images/thumbnails/theimpossiblequiz2.jpg", genre: "puzzle" },
  { title: "the legend of zelda", url: "https://bucket2.8classes.com/games/thelegendofzelda/index.html", img: "./images/thumbnails/thelegendofzelda.jpg", genre: "adventure" },
  { title: "the sims 2", url: "https://bucket2.8classes.com/games/thesims2/index.html", img: "./images/thumbnails/thesims2.jpg", genre: "simulation" },
  { title: "the sims 3", url: "https://bucket2.8classes.com/games/thesims3/index.html", img: "./images/thumbnails/thesims3.jpg", genre: "simulation" },
  { title: "theme hotel", url: "https://bucket2.8classes.com/games/themehotel/index.html", img: "./images/thumbnails/themehotel.jpg", genre: "simulation" },
  { title: "there is no game", url: "https://bucket2.8classes.com/games/thereisnogame/index.html", img: "./images/thumbnails/thereisnogame.jpg", genre: "mobile" },
  { title: "this is the only level", url: "https://bucket2.8classes.com/games/thisistheonlylevel/index.html", img: "./images/thumbnails/thisistheonlylevel.jpg", genre: "platformer" },
  { title: "three line", url: "https://bucket2.8classes.com/games/3line/index.html", img: "./images/thumbnails/threeline.jpg", genre: "puzzle" },
  { title: "thumb fighter", url: "https://bucket2.8classes.com/games/thumbfighter/index.html", img: "./images/thumbnails/thumbfighter.jpg", genre: "arcade" },
  { title: "time shooter", url: "https://bucket2.8classes.com/games/timeshooter1/index.html", img: "./images/thumbnails/timeshooter.jpg", genre: "arcade" },
  { title: "time shooter 2", url: "https://bucket2.8classes.com/games/timeshooter2/index.html", img: "./images/thumbnails/timeshooter2.jpg", genre: "arcade" },
  { title: "time shooter 3", url: "https://bucket2.8classes.com/games/timeshooter3/index.html", img: "./images/thumbnails/timeshooter3.jpg", genre: "arcade" },
  { title: "time sphere", url: "https://bucket2.8classes.com/games/timesphere/index.html", img: "./images/thumbnails/timesphere.png", genre: "arcade" },
  { title: "tiny fishing", url: "https://bucket2.8classes.com/games/tinyfishing/index.html", img: "./images/thumbnails/tinyfishing.jpg", genre: "arcade" },
  { title: "totally accurate battle sim", url: "https://bucket2.8classes.com/games/tabs/index.html", img: "./images/thumbnails/totallyaccuratebattlesim.jpg", genre: "simulation" },
  { title: "townscaper", url: "https://bucket2.8classes.com/games/townscaper/index.html", img: "./images/thumbnails/townscaper.jpg", genre: "simulator" },
  { title: "tron", url: "https://bucket2.8classes.com/games/tron/index.html", img: "./images/thumbnails/tron.jpg", genre: "arcade" },
  { title: "tube jumpers", url: "https://bucket2.8classes.com/games/tubejumpers/index.html", img: "./images/thumbnails/tubejumpers.jpg", genre: "arcade" },
  { title: "tunnel rush", url: "https://bucket2.8classes.com/games/tunnelrush/index.html", img: "./images/thumbnails/tunnelrush.jpg", genre: "arcade" },
  { title: "turok dinosaur hunter", url: "https://bucket2.8classes.com/games/turokdinosaurhunter/index.html", img: "./images/thumbnails/turokdinosaurhunter.jpg", genre: "arcade" },
  { title: "twin shot", url: "https://bucket2.8classes.com/games/twinshot/index.html", img: "./images/thumbnails/twinshot.jpg", genre: "adventure" },
  { title: "twin shot 2", url: "https://bucket2.8classes.com/games/twinshot2/index.html", img: "./images/thumbnails/twinshot2.jpg", genre: "adventure" },
  { title: "ultimate flash sonic", url: "https://bucket2.8classes.com/games/ultimateflashsonic/index.html", img: "./images/thumbnails/ultimateflashsonic.jpg", genre: "platformer" },
  { title: "unfair mario", url: "https://bucket2.8classes.com/games/unfairmario/index.html", img: "./images/thumbnails/unfairmario.jpg", genre: "platformer" },
  { title: "vectorman", url: "https://bucket2.8classes.com/games/vectorman/index.html", img: "./images/thumbnails/vectorman.jpg", genre: "arcade" },
  { title: "vectorman 2", url: "https://bucket2.8classes.com/games/vectorman2/index.html", img: "./images/thumbnails/vectorman2.jpg", genre: "arcade" },
  { title: "vex", url: "https://bucket2.8classes.com/games/vex/index.html", img: "./images/thumbnails/vex.jpg", genre: "platformer" },
  { title: "vex 2", url: "https://bucket2.8classes.com/games/vex2/index.html", img: "./images/thumbnails/vex2.jpg", genre: "platformer" },
  { title: "vex 3", url: "https://bucket2.8classes.com/games/vex3/index.html", img: "./images/thumbnails/vex3.jpg", genre: "platformer" },
  { title: "vex 4", url: "https://bucket2.8classes.com/games/vex4/index.html", img: "./images/thumbnails/vex4.jpg", genre: "platformer" },
  { title: "vex 5", url: "https://bucket2.8classes.com/games/vex5/index.html", img: "./images/thumbnails/vex5.jpg", genre: "platformer" },
  { title: "vex 6", url: "https://bucket2.8classes.com/games/vex6/index.html", img: "./images/thumbnails/vex6.jpg", genre: "platformer" },
  { title: "vex 7", url: "https://bucket2.8classes.com/games/vex7/index.html", img: "./images/thumbnails/vex7.jpg", genre: "platformer" },
  { title: "volley random", url: "https://bucket2.8classes.com/games/volleyrandom/index.html", img: "./images/thumbnails/volleyrandom.jpg", genre: "arcade" },
  { title: "wall smash", url: "https://bucket2.8classes.com/games/wallsmash/index.html", img: "./images/thumbnails/wallsmash.jpg", genre: "arcade" },
  { title: "wario land 4", url: "https://bucket2.8classes.com/games/warioland4/index.html", img: "./images/thumbnails/warioland4.jpg", genre: "platformer" },
  { title: "wario land ii", url: "https://bucket2.8classes.com/games/wariolandii/index.html", img: "./images/thumbnails/wariolandii.jpg", genre: "arcade" },
  { title: "wario's woods", url: "https://bucket2.8classes.com/games/warioswoods/index.html", img: "./images/thumbnails/warioswoods.jpg", genre: "adventure" },
  { title: "warioware", url: "https://bucket2.8classes.com/games/warioware/index.html", img: "./images/thumbnails/warioware.jpg", genre: "arcade" },
  { title: "warioware diy", url: "https://bucket2.8classes.com/games/wariowarediy/index.html", img: "./images/thumbnails/wariowarediy.jpg", genre: "arcade" },
  { title: "warioware touched", url: "https://bucket2.8classes.com/games/wariowaretouched/index.html", img: "./images/thumbnails/wariowaretouched.jpg", genre: "arcade" },
  { title: "watermelon game", url: "https://bucket2.8classes.com/games/watermelongame/index.html", img: "./images/thumbnails/watermelongame.jpg", genre: "arcade" },
  { title: "waterworks", url: "https://bucket2.8classes.com/games/waterworks/index.html", img: "./images/thumbnails/waterworks.jpg", genre: "simulation" },
  { title: "wave race 64", url: "https://bucket2.8classes.com/games/waverace64/index.html", img: "./images/thumbnails/waveracing.jpg", genre: "arcade" },
  { title: "wordle", url: "https://bucket2.8classes.com/games/wordle/index.html", img: "./images/thumbnails/wordle.jpg", genre: "arcade" },
  { title: "world's hardest game", url: "https://bucket2.8classes.com/games/worldshardestgame/index.html", img: "./images/thumbnails/worldshardestgame.jpg", genre: "puzzle" },
  { title: "worlds hardest game 2", url: "https://bucket2.8classes.com/games/worldshardestgame2/index.html", img: "./images/thumbnails/worldshardestgame2.jpg", genre: "platformer" },
  { title: "worms world party", url: "https://bucket2.8classes.com/games/wormsworldparty/index.html", img: "./images/thumbnails/wormsworldparty.jpg", genre: "adventure" },
  { title: "wubzzys adventure", url: "https://bucket2.8classes.com/games/wubzzysamazingadventure/index.html", img: "./images/thumbnails/wubzzysamazingadventure.jpg", genre: "platformer" },
  { title: "windows 11", url: "https://bucket2.8classes.com/games/apps/windows11/index.html", img: "./images/thumbnails/windows11.jpg", genre: "apps" },
  { title: "xx142-b2.exe", url: "https://bucket2.8classes.com/games/xx142-b2.exe/index.html", img: "./images/thumbnails/xx142b2.exe.jpg", genre: "arcade" },
  { title: "yohoho io", url: "https://bucket2.8classes.com/games/yohoho/index.html", img: "./images/thumbnails/yohoho.jpg", genre: "mobile" },
  { title: "yoshi's island", url: "https://bucket2.8classes.com/games/yoshisisland/index.html", img: "./images/thumbnails/yoshisisland.jpg", genre: "platformer" },
  { title: "yoshi's story", url: "https://bucket2.8classes.com/games/yoshisstory/index.html", img: "./images/thumbnails/yoshisstory.jpg", genre: "adventure" },
  { title: "zombocalypse", url: "https://bucket2.8classes.com/games/zombocalypse/index.html", img: "./images/thumbnails/zombocalpyse.jpg", genre: "arcade" },
  { title: "zombotron", url: "https://bucket2.8classes.com/games/zombotron/index.html", img: "./images/thumbnails/zombotron.jpg", genre: "adventure" },
  { title: "zombotron 2", url: "https://bucket2.8classes.com/games/zombotron2/index.html", img: "./images/thumbnails/zombotron2.jpg", genre: "adventure" }
];
